#!/bin/bash
# Generated by Copilot
# Script para testar acesso ao cluster AKS com Cross-Tenant RBAC

set -euo pipefail

# Configurações do cluster existente
PRINCIPAL_TENANT_ID="83d6df9e-eec5-4d37-be60-97bf712d85ab"
EXTERNAL_TENANT_ID="cdbba3b9-3344-40cd-9f2d-5a463efc272d"
RESOURCE_GROUP="rg-shipping-dronedelivery-eastus2"
CLUSTER_NAME="aks-2hptu3pqac3xy"
SUBSCRIPTION_ID="1e57ee4b-1c01-4752-9866-527cf3136b2d"
GROUP_ID="93ae7ed7-8077-4ed4-9947-ca3e991a253f"

# Cores para output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }

echo "======================================================="
echo "  TESTE DE ACESSO AO CLUSTER AKS CROSS-TENANT"
echo "======================================================="
echo ""
echo "🎯 Cluster: $CLUSTER_NAME"
echo "🏢 Resource Group: $RESOURCE_GROUP"
echo "🆔 Tenant Principal: $PRINCIPAL_TENANT_ID"
echo "🌐 Tenant Entra External: $EXTERNAL_TENANT_ID"
echo "👥 Grupo RBAC: $GROUP_ID"
echo ""

# Verificar se usuário está logado no tenant correto
log "Verificando tenant atual..."
CURRENT_TENANT=$(az account show --query tenantId -o tsv 2>/dev/null || echo "")

if [[ "$CURRENT_TENANT" != "$EXTERNAL_TENANT_ID" ]]; then
    warn "Você não está logado no tenant Entra ID External"
    log "Fazendo login no tenant correto..."
    az login --tenant $EXTERNAL_TENANT_ID --allow-no-subscriptions
else
    success "Você está logado no tenant Entra ID External"
fi

# Verificar membership no grupo
log "Verificando membership no grupo RBAC..."
USER_ID=$(az ad signed-in-user show --query id -o tsv)
IS_MEMBER=$(az ad group member check --group $GROUP_ID --member-id $USER_ID --query value -o tsv)

if [[ "$IS_MEMBER" == "true" ]]; then
    success "✅ Você é membro do grupo dronedelivery-cluster-admin"
else
    error "❌ Você NÃO é membro do grupo. Adicionando agora..."
    az ad group member add --group $GROUP_ID --member-id $USER_ID
    success "✅ Adicionado ao grupo com sucesso"
fi

# Configurar acesso ao cluster
log "Configurando acesso ao cluster AKS..."

# Selecionar subscription do tenant principal
az account set --subscription $SUBSCRIPTION_ID

# Obter credenciais do cluster
az aks get-credentials \
    --resource-group $RESOURCE_GROUP \
    --name $CLUSTER_NAME \
    --overwrite-existing

success "Credenciais do cluster configuradas"

echo ""
echo "======================================================="
echo "  TESTANDO ACESSO AO CLUSTER"
echo "======================================================="

# Teste 1: Verificar identidade
log "Teste 1: Verificando identidade no cluster..."
kubectl auth whoami || warn "Falha na verificação de identidade"

echo ""

# Teste 2: Listar nodes
log "Teste 2: Listando nodes do cluster..."
kubectl get nodes || warn "Falha ao listar nodes"

echo ""

# Teste 3: Verificar namespaces
log "Teste 3: Listando namespaces..."
kubectl get namespaces || warn "Falha ao listar namespaces"

echo ""

# Teste 4: Verificar RBAC
log "Teste 4: Verificando permissões RBAC..."
kubectl auth can-i "*" "*" --all-namespaces || warn "Permissões limitadas"

echo ""
echo "======================================================="
echo "  INFORMAÇÕES DO CLUSTER"
echo "======================================================="

# Mostrar informações do cluster
kubectl cluster-info 2>/dev/null || warn "Falha ao obter informações do cluster"

echo ""
echo "======================================================="
echo "  PRÓXIMOS PASSOS"
echo "======================================================="
echo ""
echo "✅ Cluster configurado com Cross-Tenant RBAC ativo"
echo "🌐 Tenant Entra External: $EXTERNAL_TENANT_ID"
echo "👥 Grupo de administradores: dronedelivery-cluster-admin"
echo ""
echo "📝 Para adicionar novos usuários:"
echo "   1. Login no tenant Entra External:"
echo "      az login --tenant $EXTERNAL_TENANT_ID" --allow-no-subscriptions
echo ""
echo "   2. Adicionar usuário ao grupo:"
echo "      az ad group member add \\"
echo "        --group \"$GROUP_ID\" \\"
echo "        --member-id <USER_OBJECT_ID>"
echo ""
echo "   3. Usuário deve fazer login e obter credenciais:"
echo "      az login --tenant $EXTERNAL_TENANT_ID" --allow-no-subscriptions
echo "      az account set --subscription $SUBSCRIPTION_ID"
echo "      az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME"
echo ""

success "🎉 Teste de acesso concluído!"
