#!/bin/bash
# Generated by Copilot
# Script para validar implementação da migração do Azure Firewall SKU

set -e

echo "🔍 Validando implementação da migração do Azure Firewall SKU..."

# Verificar se os arquivos foram modificados corretamente
echo "✅ Verificando modificações nos arquivos Bicep..."

# Verificar se o parâmetro environmentName foi adicionado
if grep -q "param environmentName string" infra/modules/networking/main.bicep; then
  echo "✅ Parâmetro environmentName adicionado ao módulo networking"
else
  echo "❌ Parâmetro environmentName não encontrado"
  exit 1
fi

# Verificar se a lógica condicional está presente
if grep -q "var isDevEnvironment = environmentName == 'dev'" infra/modules/networking/main.bicep; then
  echo "✅ Lógica condicional para ambiente dev implementada"
else
  echo "❌ Lógica condicional não encontrada"
  exit 1
fi

# Verificar se as subnets condicionais estão implementadas
if grep -q "requiresManagementSubnet" infra/modules/networking/main.bicep; then
  echo "✅ Subnet de gerenciamento condicional implementada"
else
  echo "❌ Subnet de gerenciamento condicional não encontrada"
  exit 1
fi

# Verificar se o IP de gerenciamento está condicional
if grep -q "resource firewallManagementPublicIp.*if (requiresManagementSubnet)" infra/modules/networking/main.bicep; then
  echo "✅ IP público de gerenciamento condicional implementado"
else
  echo "❌ IP público de gerenciamento condicional não encontrado"
  exit 1
fi

# Verificar se o firewall tier está configurado condicionalmente
if grep -q "tier: firewallTier" infra/modules/networking/main.bicep; then
  echo "✅ SKU do firewall configurado condicionalmente"
else
  echo "❌ SKU do firewall não configurado condicionalmente"
  exit 1
fi

# Verificar se as regras simplificadas estão implementadas
if grep -q "isDevEnvironment ? \[" infra/modules/networking/main.bicep; then
  echo "✅ Regras simplificadas para ambiente dev implementadas"
else
  echo "❌ Regras simplificadas não implementadas"
  exit 1
fi

# Verificar se o parâmetro foi passado no main.bicep
if grep -q "environmentName: environmentName" infra/main.bicep; then
  echo "✅ Parâmetro environmentName passado para o módulo networking"
else
  echo "❌ Parâmetro environmentName não passado para o módulo"
  exit 1
fi

# Verificar se não há erros de sintaxe Bicep (se az CLI estiver disponível)
if command -v az &>/dev/null; then
  echo "📋 Validando sintaxe Bicep..."
  if az bicep build --file infra/main.bicep --stdout >/dev/null 2>&1; then
    echo "✅ Sintaxe Bicep válida"
  else
    echo "❌ Erro de sintaxe Bicep detectado"
    az bicep build --file infra/main.bicep --stdout
    exit 1
  fi
else
  echo "⚠️  Azure CLI não disponível - pulando validação de sintaxe"
fi

# Verificar o valor do environmentName no arquivo de parâmetros
ENVIRONMENT_VALUE=$(grep -A 1 '"environmentName"' infra/main.parameters.json | grep '"value"' | cut -d'"' -f4)
echo "📋 Ambiente configurado nos parâmetros: $ENVIRONMENT_VALUE"

if [ "$ENVIRONMENT_VALUE" = "dev" ]; then
  echo "✅ Ambiente configurado para 'dev' - Azure Firewall Basic será usado"
else
  echo "ℹ️  Ambiente configurado para '$ENVIRONMENT_VALUE' - Azure Firewall Standard será usado"
fi

echo ""
echo "🎉 Validação concluída com sucesso!"
echo ""
echo "📊 Resumo da implementação:"
echo "   - ✅ Lógica condicional por ambiente implementada"
echo "   - ✅ SKU Basic para ambiente dev / Standard para prod"
echo "   - ✅ Subnet de gerenciamento criada apenas para Basic SKU"
echo "   - ✅ IP público de gerenciamento criado apenas para Basic SKU"
echo "   - ✅ Regras de firewall simplificadas para ambiente dev"
echo "   - ✅ Configuração sem zonas de disponibilidade para Basic SKU"
echo ""
echo "💡 Próximos passos:"
echo "   1. Testar deployment: azd provision"
echo "   2. Validar custos no ambiente dev"
echo "   3. Testar funcionalidades do AKS"
echo "   4. Validar conectividade através do firewall"
