// Generated by Copilot
// Main Bicep template for Fabrikam Drone Delivery AKS modernized deployment
// This template orchestrates all infrastructure components using modular design

targetScope = 'subscription'

// Add location metadata for subscription-scoped deployment
metadata description = 'Fabrikam Drone Delivery AKS Infrastructure'
metadata location = 'eastus2' // Default location for subscription-scoped deployment

// ============================================================================
// PARAMETERS
// ============================================================================
@description('Suffix project')
@maxLength(4)
param suffix string
@description('Environment name (dev, staging, prod)')
@allowed(['dev', 'staging', 'prod'])
param environmentName string
@description('Primary Azure region for deployment')
param location string
param azureTenantId string
@description('Secondary region for geo-redundant services')
param geoRedundancyLocation string
@description('Tenant ID for Azure AD integration')
param k8sRbacEntraProfileTenantId string
@description('Kubernetes version for AKS cluster')
param kubernetesVersion string
@description('Node Count for AKS Node System')
param aksSystemNodeCount int
@description('Node Count for AKS User Node Pool')
param aksUserNodeCount int
@description('VM size for AKS nodes')
param aksNodeSize string
@description('Enable auto-scaling for AKS node pools')
param aksEnableAutoScaling bool
@description('Minimum node count for auto-scaling')
param aksMinCount int
@description('Maximum node count for auto-scaling')
param aksMaxCount int
@description('AKS service CIDR range')
param aksServiceCidr string
@description('AKS DNS service IP address')
param aksDnsServiceIP string
@description('Load balancer SKU for AKS')
@allowed(['Basic', 'Standard'])
param aksLoadBalancerSku string
@description('Object ID of the Azure AD group that will have admin access to AKS')
param k8sRbacEntraAdminGroupObjectID string
@description('Object ID of the current user or service principal for Key Vault access')
param currentUserObjectId string = ''
@description('Domain name for the application (e.g., fabrikam.com)')
param domainName string
@description('Application name prefix for resource naming')
param appName string
@description('Sku for Azure Container registry')
param acrSku string
@description('Consistence Level for Cosmos DB')
param dbConsistencyLevel string
@description('Replication Level for Cosmos DB')
param dbMaxIntervalInSeconds int
@description('Staleness Level for Cosmos DB')
param dbMaxStalenessPrefix int
@description('Write location enable Cosmos DB')
param dbEnableMultipleWriteLocations bool
@description('Redis SKU')
param redisSku string
@description('Redis Family')
param redisFamily string
@description('Redis Capacity')
param redisCapacity int
@description('Service Bus SKU')
param sBusSku string
@description('Service Bus Tier')
param sBusTier string
@description('Hub Vnet Address Prefix')
param hubVnetAddressPrefix string
@description('Spoke Vnet Address Prefix')
param spokeVnetAddressPrefix string
@description('Gateway Subnet Prefix')
param azureGatewaySubnetPrefix string
@description('Azure Firewall Subnet Prefix')
param azureFirewallSubnetPrefix string
@description('Bastion Subnet Prefix')
param bastionSubnetPrefix string
@description('Aks System Subnet Prefix')
param clusterNodesSubnetPrefix string
@description('Aks User Subnet Prefix')
param clusterIngressServicesSubnetPrefix string
@description('Application Gateway User Subnet Prefix')
param applicationGatewaySubnetPrefix string
// @description('Private Endpoint User Subnet Prefix')
// param privateEndpointsSubnetPrefix string
@description('Log Analitics Workspace SKU')
param logAnalyticsWorkspaceSku string
@description('Firewall Managementy Prefix for Dev env Firewall SKU Basic')
param azureFirewallManagementSubnetPrefix string
@description('Tags to be applied to all resources')
param tags object = {
  Environment: environmentName
  Application: 'Fabrikam Drone Delivery'
  'Cost Center': 'Engineering'
  Owner: 'Platform Team'
  'Deployment Method': 'Azure Developer CLI'
}

// ============================================================================
// VARIABLES
// ============================================================================

var resourceSuffix = '${appName}-${environmentName}-${suffix}'
var cleanedresourceSuffix = replace(resourceSuffix, '-', '')

var resourceGroupNames = {
  networing: 'rg-networking-${resourceSuffix}'
  compute: 'rg-compute-${resourceSuffix}'
  data: 'rg-data-${resourceSuffix}'
  security: 'rg-security-${resourceSuffix}'
  container: 'rg-container-${resourceSuffix}'
}

// ============================================================================
// RESOURCE GROUPS
// ============================================================================

resource networkingRG 'Microsoft.Resources/resourceGroups@2023-07-01' = {
  name: resourceGroupNames.networing
  location: location
  tags: tags
}

resource computeRG 'Microsoft.Resources/resourceGroups@2023-07-01' = {
  name: resourceGroupNames.compute
  location: location
  tags: tags
}

resource dataRG 'Microsoft.Resources/resourceGroups@2023-07-01' = {
  name: resourceGroupNames.data
  location: location
  tags: tags
}

resource securityRG 'Microsoft.Resources/resourceGroups@2023-07-01' = {
  name: resourceGroupNames.security
  location: location
  tags: tags
}

resource containerRG 'Microsoft.Resources/resourceGroups@2023-07-01' = {
  name: resourceGroupNames.container
  location: location
  tags: tags
}

// ============================================================================
// OBSERVABILITY MODULE (Application Insights)
// ============================================================================

module observability 'modules/observability/main.bicep' = {
  name: 'observability-deployment'
  scope: computeRG
  params: {
    location: location
    resourceSuffix: resourceSuffix
    tags: tags
    logAnalyticsWorkspaceSku: logAnalyticsWorkspaceSku
    retentionInDays: 30
  }
}

// ============================================================================
// NETWORKING MODULE
// ============================================================================

module networking 'modules/networking/main.bicep' = {
  name: 'networking-deployment'
  scope: networkingRG
  params: {
    location: location
    resourceSuffix: resourceSuffix
    environmentName: environmentName
    tags: tags
    clusterNodesSubnetPrefix: clusterNodesSubnetPrefix
    clusterIngressServicesSubnetPrefix: clusterIngressServicesSubnetPrefix
    applicationGatewaySubnetPrefix: applicationGatewaySubnetPrefix
    azureFirewallSubnetPrefix: azureFirewallSubnetPrefix
    bastionSubnetPrefix: bastionSubnetPrefix
    azureGatewaySubnetPrefix: azureGatewaySubnetPrefix
    // hubNodePoolSubnetPrefix: hubNodePoolSubnetPrefix
    hubVnetAddressPrefix: hubVnetAddressPrefix
    // privateEndpointsSubnetPrefix: privateEndpointsSubnetPrefix
    spokeVnetAddressPrefix: spokeVnetAddressPrefix
    azureFirewallManagementSubnetPrefix: azureFirewallManagementSubnetPrefix
    logAnalyticsWorkspaceId: observability.outputs.logAnalyticsWorkspaceId
    logConfigurations: observability.outputs.logConfigurationsObj
    metricsConfiguration: observability.outputs.metricsConfigurationArr
  }
}

// ============================================================================
// SECURITY MODULE (Key Vault, Managed Identities, Certificates)
// ============================================================================

module security 'modules/security/main.bicep' = {
  name: 'security-deployment'
  scope: securityRG
  params: {
    location: location
    resourceSuffix: resourceSuffix
    domainName: domainName
    tags: tags
    azureTenantId: azureTenantId
    currentUserObjectId: currentUserObjectId // Generated by Copilot - Pass current user object ID
    // Generated by Copilot - AKS identity will be handled in post-provisioning hook
  }
}

// ============================================================================
// CONTAINER REGISTRY MODULE
// ============================================================================

module containerRegistry 'modules/container/acr.bicep' = {
  name: 'container-registry-deployment'
  scope: containerRG
  params: {
    acrSku: acrSku
    location: location
    resourceSuffix: cleanedresourceSuffix
    tags: tags
  }
}

// ============================================================================
// DATA SERVICES MODULE (Cosmos DB, Redis, Service Bus)
// ============================================================================

module dataServices 'modules/data/main.bicep' = {
  name: 'data-services-deployment'
  scope: dataRG
  params: {
    location: location
    geoRedundancyLocation: geoRedundancyLocation
    environmentName: environmentName
    resourceSuffix: resourceSuffix
    tags: tags
    dbConsistencyLevel: dbConsistencyLevel
    dbEnableMultipleWriteLocations: dbEnableMultipleWriteLocations
    dbMaxIntervalInSeconds: dbMaxIntervalInSeconds
    dbMaxStalenessPrefix: dbMaxStalenessPrefix
    redisCapacity: redisCapacity
    redisFamily: redisFamily
    redisSku: redisSku
    sBusSku: sBusSku
    sBusTier: sBusTier
  }
}

// ============================================================================
// AKS CLUSTER MODULE
// ============================================================================

module aksCluster 'modules/compute/aks-cluster.bicep' = {
  name: 'aks-cluster-deployment'
  scope: computeRG
  params: {
    location: location
    resourceSuffix: resourceSuffix
    kubernetesVersion: kubernetesVersion
    aksSystemNodeCount: aksSystemNodeCount
    aksUserNodeCount: aksUserNodeCount
    aksNodeSize: aksNodeSize
    k8sRbacEntraAdminGroupObjectID: k8sRbacEntraAdminGroupObjectID
    k8sRbacEntraProfileTenantId: k8sRbacEntraProfileTenantId
    vnetResourceId: networking.outputs.spokeVnetId
    subnetResourceId: networking.outputs.aksSubnetId
    containerRegistryId: containerRegistry.outputs.registryId
    keyVaultId: security.outputs.keyVaultId
    logAnalyticsWorkspaceId: observability.outputs.logAnalyticsWorkspaceId
    aksServiceCidr: aksServiceCidr
    aksDnsServiceIP: aksDnsServiceIP
    aksEnableAutoScaling: aksEnableAutoScaling
    aksLoadBalancerSku: aksLoadBalancerSku
    aksMaxCount: aksMaxCount
    aksMinCount: aksMinCount
    tags: tags
  }
}

// ============================================================================
// WORKLOAD MODULE (Microservices deployment)
// ============================================================================

// TODO: Deploy workloads after infrastructure is complete
// module workload 'modules/workload/main.bicep' = {
//   name: 'workload-deployment'
//   scope: computeRG
//   params: {
//     aksClusterName: aksCluster.outputs.clusterName
//     containerRegistryName: containerRegistry.outputs.registryName
//   }
// }

// ============================================================================
// OUTPUTS
// ============================================================================

// Required outputs for Azure Developer CLI
output AZURE_LOCATION string = location
output AZURE_TENANT_ID string = tenant().tenantId
output AZURE_RESOURCE_GROUP string = computeRG.name
output RESOURCE_GROUP_ID string = computeRG.id
output KUBERNETES_VERSION string = kubernetesVersion
output AKS_CLUSTER_NAME string = aksCluster.outputs.clusterName

// Resource group information
output resourceGroupNames object = resourceGroupNames
output aksClusterName string = aksCluster.outputs.clusterName
output containerRegistryName string = containerRegistry.outputs.registryName
output keyVaultName string = security.outputs.keyVaultName
output applicationGatewayFqdn string = networking.outputs.applicationGatewayFqdn
output aksClusterFqdn string = aksCluster.outputs.clusterFqdn

// Application Insights outputs
output applicationInsightsId string = observability.outputs.applicationInsightsId
output applicationInsightsName string = observability.outputs.applicationInsightsName
output applicationInsightsInstrumentationKey string = observability.outputs.instrumentationKey
output applicationInsightsConnectionString string = observability.outputs.connectionString

// Application endpoints
output endpoints object = {
  applicationGateway: networking.outputs.applicationGatewayFqdn
  aksCluster: aksCluster.outputs.clusterFqdn
  containerRegistry: containerRegistry.outputs.registryLoginServer
  keyVault: security.outputs.keyVaultUri
  applicationInsights: observability.outputs.applicationInsightsName
}

// Connection information for troubleshooting
output connectionInfo object = {
  aksGetCredentials: 'az aks get-credentials --name ${aksCluster.outputs.clusterName} --resource-group ${resourceGroupNames.compute}'
  acrLogin: 'az acr login --name ${containerRegistry.outputs.registryName}'
  keyVaultAccess: 'az keyvault show --name ${security.outputs.keyVaultName}'
  applicationInsights: 'az monitor app-insights show --app ${observability.outputs.applicationInsightsName} --resource-group ${resourceGroupNames.compute}'
}
