#!/bin/bash
# Generated by Copilot
# Test script for TLS certificate generation in preprovision hook

set -e

echo "🧪 Testing TLS certificate generation implementation..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
  echo -e "${BLUE}ℹ️  $1${NC}"
}

log_success() {
  echo -e "${GREEN}✅ $1${NC}"
}

log_error() {
  echo -e "${RED}❌ $1${NC}"
}

# Test certificate generation functions
test_certificate_functions() {
  log_info "Testing certificate generation functions..."

  # Create temporary test directory
  TEST_DIR="./test_certificates"
  mkdir -p "$TEST_DIR"
  cd "$TEST_DIR"

  # Test Application Gateway certificate generation
  log_info "Testing Application Gateway certificate generation..."
  openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -out test_appgw.crt \
    -keyout test_appgw.key \
    -subj "/CN=dronedelivery.fabrikam.com/O=Fabrikam Drone Delivery" 2>/dev/null

  if [ -f "test_appgw.crt" ] && [ -f "test_appgw.key" ]; then
    log_success "Application Gateway certificate generation test passed"
  else
    log_error "Application Gateway certificate generation test failed"
    cleanup_test
    exit 1
  fi

  # Test PFX conversion
  log_info "Testing PFX conversion..."
  openssl pkcs12 -export -out test_appgw.pfx \
    -in test_appgw.crt \
    -inkey test_appgw.key \
    -passout pass: 2>/dev/null

  if [ -f "test_appgw.pfx" ]; then
    log_success "PFX conversion test passed"
  else
    log_error "PFX conversion test failed"
    cleanup_test
    exit 1
  fi

  # Test Base64 encoding
  log_info "Testing Base64 encoding..."
  TEST_B64=$(cat test_appgw.pfx | base64 | tr -d '\n')

  if [ -n "$TEST_B64" ] && [ ${#TEST_B64} -gt 100 ]; then
    log_success "Base64 encoding test passed"
  else
    log_error "Base64 encoding test failed"
    cleanup_test
    exit 1
  fi

  # Test AKS Ingress Controller certificate
  log_info "Testing AKS Ingress Controller certificate generation..."
  openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -out test_k8sic.crt \
    -keyout test_k8sic.key \
    -subj "/CN=*.aks-agic.fabrikam.com/O=Fabrikam Aks Ingress" 2>/dev/null

  if [ -f "test_k8sic.crt" ] && [ -f "test_k8sic.key" ]; then
    log_success "AKS Ingress Controller certificate generation test passed"
  else
    log_error "AKS Ingress Controller certificate generation test failed"
    cleanup_test
    exit 1
  fi

  # Test certificate validation
  log_info "Testing certificate validation..."
  APP_CN=$(openssl x509 -in test_appgw.crt -noout -subject | sed -n 's/.*CN[[:space:]]*=[[:space:]]*\([^,]*\).*/\1/p')
  INGRESS_CN=$(openssl x509 -in test_k8sic.crt -noout -subject | sed -n 's/.*CN[[:space:]]*=[[:space:]]*\([^,]*\).*/\1/p')

  if [ "$APP_CN" = "dronedelivery.fabrikam.com" ] && [ "$INGRESS_CN" = "*.aks-agic.fabrikam.com" ]; then
    log_success "Certificate validation test passed"
  else
    log_error "Certificate validation test failed - CN mismatch"
    log_error "Expected App GW CN: dronedelivery.fabrikam.com, got: $APP_CN"
    log_error "Expected Ingress CN: *.aks-agic.fabrikam.com, got: $INGRESS_CN"
    cleanup_test
    exit 1
  fi

  cleanup_test
  log_success "All certificate generation tests passed!"
}

# Cleanup test files
cleanup_test() {
  cd ..
  rm -rf "$TEST_DIR"
}

# Test prerequisites
test_prerequisites() {
  log_info "Testing prerequisites..."

  # Test OpenSSL
  if command -v openssl &>/dev/null; then
    log_success "OpenSSL is available"
  else
    log_error "OpenSSL is not available"
    exit 1
  fi

  # Test Base64
  if command -v base64 &>/dev/null; then
    log_success "Base64 encoding is available"
  else
    log_error "Base64 encoding is not available"
    exit 1
  fi

  log_success "Prerequisites test passed!"
}

# Test environment variables format
test_env_variables() {
  log_info "Testing environment variable formats..."

  # Test if azd command exists (optional)
  if command -v azd &>/dev/null; then
    log_success "AZD CLI is available for environment variable storage"
  else
    log_info "AZD CLI not available - will test format only"
  fi

  # Test variable name format
  TEST_VAR_NAME="APP_GATEWAY_LISTENER_CERTIFICATE"
  if [[ "$TEST_VAR_NAME" =~ ^[A-Z_][A-Z0-9_]*$ ]]; then
    log_success "Environment variable naming format is correct"
  else
    log_error "Environment variable naming format is incorrect"
    exit 1
  fi

  log_success "Environment variable tests passed!"
}

# Main test execution
main() {
  echo ""
  echo "================================================="
  echo "  🧪 TLS Certificate Generation Test Suite"
  echo "================================================="
  echo ""

  test_prerequisites
  test_env_variables
  test_certificate_functions

  echo ""
  log_success "🎉 All tests passed! Certificate generation is ready for production use."
  echo ""
  echo "📋 What was tested:"
  echo "   ✅ OpenSSL certificate generation"
  echo "   ✅ PFX conversion for Azure Application Gateway"
  echo "   ✅ Base64 encoding for Key Vault storage"
  echo "   ✅ Wildcard certificate for AKS Ingress Controller"
  echo "   ✅ Certificate validation and CN verification"
  echo "   ✅ Environment variable format compliance"
  echo ""
  echo "🚀 Ready to integrate with preprovision.sh!"
  echo ""
}

# Run tests
main "$@"
