// Generated by Copilot
// filepath: /home/cmac/workspace/aks-fabrikam-dronedelivery/infra/modules/observability/diagnosticSettings.bicep

@description('Nome do diagnostic setting')
param name string

@description('ID do Log Analytics Workspace')
param workspaceId string

@description('ID do recurso para o qual criar diagnostic settings')
param targetResourceId string

@description('Tipo do recurso para configurações específicas')
param resourceType string = 'generic'

// Configurações específicas por tipo de recurso
var logConfigurations = {
  aks: [
    {
      category: 'kube-apiserver'
      enabled: true
    }
    {
      category: 'kube-audit'
      enabled: true
    }
    {
      category: 'kube-audit-admin'
      enabled: true
    }
    {
      category: 'kube-controller-manager'
      enabled: true
    }
    {
      category: 'kube-scheduler'
      enabled: true
    }
    {
      category: 'cluster-autoscaler'
      enabled: true
    }
    {
      category: 'guard'
      enabled: true
    }
  ]
  appgateway: [
    {
      category: 'ApplicationGatewayAccessLog'
      enabled: true
    }
    {
      category: 'ApplicationGatewayPerformanceLog'
      enabled: true
    }
    {
      category: 'ApplicationGatewayFirewallLog'
      enabled: true
    }
  ]
  keyvault: [
    {
      category: 'AuditEvent'
      enabled: true
    }
    {
      category: 'AzurePolicyEvaluationDetails'
      enabled: true
    }
  ]
  generic: [
    {
      categoryGroup: 'AllLogs'
      enabled: true
    }
  ]
}

// Configurações de métricas
var metricsConfiguration = [
  {
    category: 'AllMetrics'
    enabled: true
  }
]

// Generated by Copilot - Reference to existing resource
resource targetResource 'Microsoft.Resources/resourceGroups@2021-04-01' existing = {
  name: split(targetResourceId, '/')[4]
  scope: subscription()
}

// Generated by Copilot - Diagnostic Settings Resource
resource diagnosticSetting 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: name
  scope: resourceSymbolicName(targetResourceId)
  properties: {
    workspaceId: workspaceId
    logs: logConfigurations[?resourceType] ?? logConfigurations.generic
    metrics: metricsConfiguration
  }
}
func resourceSymbolicName(resourceId string<resource>) string<resource> => resourceId
