// Generated by Copilot
// Data services module - Cosmos DB, Redis Cache, Service Bus
targetScope = 'resourceGroup'

// ============================================================================
// PARAMETERS
// ============================================================================

@description('Primary deployment location')
param location string = resourceGroup().location
@description('Secondary location for geo-redundancy')
param geoRedundancyLocation string
@description('Environment name (dev, staging, prod)')
param environmentName string
@description('Resource prefix identifier for resource naming')
param resourceSuffix string
@description('Consistence Level for Cosmos DB')
param dbConsistencyLevel string
@description('Replication Level for Cosmos DB')
param dbMaxIntervalInSeconds int
@description('Staleness Level for Cosmos DB')
param dbMaxStalenessPrefix int
@description('Write location enable Cosmos DB')
param dbEnableMultipleWriteLocations bool
@description('Redis SKU')
param redisSku string
@description('Redis Family')
param redisFamily string
@description('Redis Capacity')
param redisCapacity int
@description('Service Bus SKU')
param sBusSku string
@description('Service Bus Tier')
param sBusTier string
@description('Resource tags')
param tags object

// ============================================================================
// VARIABLES
// ============================================================================
var deliveryCosmosDbAccountName = 'cosmos-delivery-${resourceSuffix}'
var droneSchedulerCosmosDbName = 'cosmos-scheduler-${resourceSuffix}'
var packageMongoCosmosDbName = 'cosmon-package-${resourceSuffix}'
var deliveryRedisName = 'redis-delivery-${resourceSuffix}'
var serviceBusNamespaceName = 'sbns-ingest-${resourceSuffix}'
var serviceBusQueueName = 'sbqueue-ingest-${resourceSuffix}'
// ============================================================================
// COSMOS DB ACCOUNTS
// ============================================================================
// Cosmos DB account for delivery service
resource deliveryCosmosDb 'Microsoft.DocumentDB/databaseAccounts@2023-09-15' = {
  name: deliveryCosmosDbAccountName
  location: location
  tags: union(tags, { 'azd-service-name': 'Delivery-CosmosDb-Document' })
  kind: 'GlobalDocumentDB'
  properties: {
    consistencyPolicy: {
      defaultConsistencyLevel: dbConsistencyLevel
      maxIntervalInSeconds: dbMaxIntervalInSeconds
      maxStalenessPrefix: dbMaxStalenessPrefix
    }
    locations: environmentName == 'dev'
      ? [
          {
            locationName: location
            failoverPriority: 0
            isZoneRedundant: false
          }
        ]
      : [
          {
            locationName: location
            failoverPriority: 0
            isZoneRedundant: true
          }
          {
            locationName: geoRedundancyLocation
            failoverPriority: 1
            isZoneRedundant: true
          }
        ]
    databaseAccountOfferType: 'Standard'
    enableMultipleWriteLocations: dbEnableMultipleWriteLocations
    isVirtualNetworkFilterEnabled: false
    virtualNetworkRules: []
    disableKeyBasedMetadataWriteAccess: false
    enableFreeTier: environmentName == 'dev'
    enableAutomaticFailover: environmentName != 'dev'
    capabilities: []
    ipRules: []
  }
}
// Cosmos DB account for drone scheduler service
resource droneSchedulerCosmosDb 'Microsoft.DocumentDB/databaseAccounts@2023-09-15' = {
  name: droneSchedulerCosmosDbName
  location: location
  tags: union(tags, { 'azd-service-name': 'Drone-Scheduler-CosmosDB' })
  kind: 'GlobalDocumentDB'
  properties: {
    consistencyPolicy: {
      defaultConsistencyLevel: dbConsistencyLevel
      maxIntervalInSeconds: dbMaxIntervalInSeconds
      maxStalenessPrefix: dbMaxStalenessPrefix
    }
    locations: environmentName == 'dev'
      ? [
          {
            locationName: location
            failoverPriority: 0
            isZoneRedundant: false
          }
        ]
      : [
          {
            locationName: location
            failoverPriority: 0
            isZoneRedundant: true
          }
          {
            locationName: geoRedundancyLocation
            failoverPriority: 1
            isZoneRedundant: true
          }
        ]
    databaseAccountOfferType: 'Standard'
    enableMultipleWriteLocations: dbEnableMultipleWriteLocations
    isVirtualNetworkFilterEnabled: false
    virtualNetworkRules: []
    disableKeyBasedMetadataWriteAccess: false
    enableFreeTier: environmentName == 'dev'
    enableAutomaticFailover: environmentName != 'dev'
    capabilities: []
    ipRules: []
  }
}
// MongoDB API Cosmos DB for Package service
resource packageCosmosMongoDb 'Microsoft.DocumentDB/databaseAccounts@2023-09-15' = {
  name: packageMongoCosmosDbName
  location: location
  tags: union(tags, { 'azd-service-name': 'Package-CosmosDB-Mongo' })
  kind: 'MongoDB'
  properties: {
    consistencyPolicy: {
      defaultConsistencyLevel: dbConsistencyLevel
      maxIntervalInSeconds: dbMaxIntervalInSeconds
      maxStalenessPrefix: dbMaxStalenessPrefix
    }
    locations: [
      {
        locationName: location
        failoverPriority: 0
        isZoneRedundant: environmentName != 'dev'
      }
    ]
    databaseAccountOfferType: 'Standard'
    apiProperties: {
      serverVersion: '7.0'
    }
    isVirtualNetworkFilterEnabled: false
    virtualNetworkRules: []
    disableKeyBasedMetadataWriteAccess: false
    enableFreeTier: environmentName == 'dev'
    enableAutomaticFailover: environmentName != 'dev'
    capabilities: [
      {
        name: 'EnableMongo'
      }
    ]
    ipRules: []
  }
}
// ============================================================================
// REDIS CACHE
// ============================================================================
resource deliveryRedisCache 'Microsoft.Cache/redis@2023-08-01' = {
  name: deliveryRedisName
  location: location
  tags: union(tags, { 'azd-service-name': 'Delivery-Redis' })
  properties: {
    sku: {
      name: redisSku
      family: redisFamily
      capacity: redisCapacity
    }
    enableNonSslPort: false
    minimumTlsVersion: '1.2'
    redisConfiguration: {
      'maxmemory-policy': 'allkeys-lru'
    }
    redisVersion: '6'
    publicNetworkAccess: 'Enabled'
  }
}
// ============================================================================
// SERVICE BUS
// ============================================================================
resource serviceBusNamespace 'Microsoft.ServiceBus/namespaces@2022-10-01-preview' = {
  name: serviceBusNamespaceName
  location: location
  tags: union(
    tags,
    { 'azd-service-name': 'Ingestion-Workflow-ServiceBus', app: 'fabrikam-ingestion and fabrikam-workflow' }
  )
  sku: {
    name: sBusSku
    tier: sBusTier
  }
  properties: {
    minimumTlsVersion: '1.2'
    publicNetworkAccess: 'Enabled'
    disableLocalAuth: false
    zoneRedundant: environmentName == 'prod'
  }
}
resource serviceBusQueue 'Microsoft.ServiceBus/namespaces/queues@2022-10-01-preview' = {
  parent: serviceBusNamespace
  name: serviceBusQueueName
  properties: union(
    {
      lockDuration: 'PT1M'
      maxSizeInMegabytes: 1024
      requiresDuplicateDetection: false
      requiresSession: false
      defaultMessageTimeToLive: 'P14D'
      deadLetteringOnMessageExpiration: true
      duplicateDetectionHistoryTimeWindow: 'PT10M'
      maxDeliveryCount: 10
      enablePartitioning: false
      enableExpress: false
    },
    sBusTier != 'Basic'
      ? {
          autoDeleteOnIdle: 'P10675199DT2H48M5.4775807S'
        }
      : {}
  )
}
// Service Bus authorization rules
resource serviceBusListenRule 'Microsoft.ServiceBus/namespaces/AuthorizationRules@2022-10-01-preview' = {
  parent: serviceBusNamespace
  name: 'IngestionServiceAccessKey'
  properties: {
    rights: [
      'Send'
    ]
  }
}
resource serviceBusSendRule 'Microsoft.ServiceBus/namespaces/AuthorizationRules@2022-10-01-preview' = {
  parent: serviceBusNamespace
  name: 'WorkflowServiceAccessKey'
  properties: {
    rights: [
      'Listen'
    ]
  }
}
// ============================================================================
// OUTPUTS
// ============================================================================
output servicesConfig object = {
  deliveryCosmosDb: {
    accountName: deliveryCosmosDb.name
    endpoint: deliveryCosmosDb.properties.documentEndpoint
    primaryKey: deliveryCosmosDb.listKeys().primaryMasterKey
    connectionString: 'AccountEndpoint=${deliveryCosmosDb.properties.documentEndpoint};AccountKey=${deliveryCosmosDb.listKeys().primaryMasterKey};'
  }
  droneSchedulerCosmosDb: {
    accountName: droneSchedulerCosmosDb.name
    endpoint: droneSchedulerCosmosDb.properties.documentEndpoint
    primaryKey: droneSchedulerCosmosDb.listKeys().primaryMasterKey
    connectionString: 'AccountEndpoint=${droneSchedulerCosmosDb.properties.documentEndpoint};AccountKey=${droneSchedulerCosmosDb.listKeys().primaryMasterKey};'
  }
  packageCosmonDb: {
    accountName: packageCosmosMongoDb.name
    endpoint: packageCosmosMongoDb.properties.documentEndpoint
    connectionString: packageCosmosMongoDb.listConnectionStrings().connectionStrings[0].connectionString
  }
  redisCache: {
    name: deliveryRedisCache.name
    hostName: deliveryRedisCache.properties.hostName
    port: deliveryRedisCache.properties.port
    sslPort: deliveryRedisCache.properties.sslPort
    primaryKey: deliveryRedisCache.listKeys().primaryKey
    connectionString: '${deliveryRedisCache.properties.hostName}:${deliveryRedisCache.properties.sslPort},password=${deliveryRedisCache.listKeys().primaryKey},ssl=True,abortConnect=False'
  }
  serviceBus: {
    namespaceName: serviceBusNamespace.name
    endpoint: 'https://${serviceBusNamespace.name}.servicebus.windows.net/'
    queueName: serviceBusQueue.name
    ingestionConnectionString: serviceBusListenRule.listKeys().primaryConnectionString
    workflowConnectionString: serviceBusSendRule.listKeys().primaryConnectionString
  }
}
// Individual service outputs for reference
output deliveryCosmosDbAccountName string = deliveryCosmosDb.name
output deliveryCosmosDbEndpoint string = deliveryCosmosDb.properties.documentEndpoint
output droneSchedulerCosmosDbAccountName string = droneSchedulerCosmosDb.name
output droneSchedulerCosmosDbEndpoint string = droneSchedulerCosmosDb.properties.documentEndpoint
output packageCosmosMongoDbName string = packageCosmosMongoDb.name
output redisName string = deliveryRedisCache.name
output serviceBusNamespaceName string = serviceBusNamespace.name
