#!/bin/bash
# Generated by Copilot
# Pre-provisioning hook for Fabrikam Drone Delivery AKS deployment
# This script runs before the main Bicep deployment

set -e

echo "🚀 Starting pre-provisioning setup..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
  echo -e "${BLUE}ℹ️  $1${NC}"
}

log_success() {
  echo -e "${GREEN}✅ $1${NC}"
}

log_warning() {
  echo -e "${YELLOW}⚠️  $1${NC}"
}

log_error() {
  echo -e "${RED}❌ $1${NC}"
}
#carrega um ambiente especifico (dev, hml,prd)
environmentName=$(azd env get-values | grep "environmentName=" | cut -d '=' -f2 | tr -d '"')
if [[ -z "$environmentName" ]]; then
  echo -e "${RED}❌ Variável environmentName não definida no azd!${NC}"
  exit 1
fi
envFile=".azure/$AZURE_ENV_NAME/.env"
if [[ ! -f "$envFile" ]]; then
  echo -e "${RED}❌ Arquivo .env não encontrado: $envFile${NC}"
  exit 1
else
  source "$envFile"
  echo -e "${GREEN}✅ Arquivo .env carregado!${NC}"
fi
# Check prerequisites
check_prerequisites() {
  log_info "Checking prerequisites..."
  # Check if Azure CLI is installed
  if ! command -v az &>/dev/null; then
    log_error "Azure CLI is not installed. Please install it first."
    exit 1
  fi
  # Check if user is logged in
  if ! az account show &>/dev/null; then
    log_error "Not logged into Azure. Please run 'az login' first."
    exit 1
  fi
  # Check if kubectl is installed
  if ! command -v kubectl &>/dev/null; then
    log_warning "kubectl is not installed. It will be needed after deployment."
  fi
  # Check if helm is installed
  if ! command -v helm &>/dev/null; then
    log_warning "Helm is not installed. It will be needed for workload deployment."
  fi
  log_success "Prerequisites check completed"
}
# Validate Azure subscription and permissions
validate_permissions() {
  log_info "Validating Azure permissions..."
  # Get current subscription
  log_info "Current subscription: $azureSubscriptionId"
  log_info "Current tenant: $azureTenantId"
  # Check if user has required permissions (Contributor + User Access Administrator)
  # This is a simplified check - in production you might want more thorough validation
  USER_OBJECT_ID=$(az ad signed-in-user show --query id -o tsv)
  if [ -z "$USER_OBJECT_ID" ]; then
    log_error "Unable to get current user information"
    exit 1
  fi
  log_success "Permission validation completed"
}
# Set required environment variables for azd
check_environment_variables() {
  log_info "Checking up environment variables..."

  # Generated by Copilot - Set AZURE_LOCATION for azd
  if [ -z "$(azd env get-value AZURE_LOCATION 2>/dev/null)" ]; then
    azd env set AZURE_LOCATION "$location"
    log_info "Set AZURE_LOCATION to $location"
  fi

  # Generated by Copilot - Set AZURE_ENV_NAME for azd
  if [ -z "$(azd env get-value AZURE_ENV_NAME 2>/dev/null)" ]; then
    azd env set AZURE_ENV_NAME "$environmentName"
    log_info "Set AZURE_ENV_NAME to $environmentName"
  fi

  # Get Azure AD group for AKS admin access
  if [ -z "$k8sRbacEntraAdminGroupObjectID" ]; then
    azd env set k8sRbacEntraAdminGroupObjectID "93ae7ed7-8077-4ed4-9947-ca3e991a253f"
    log_info "Set AD Group for AKS admin Access to 93ae7ed7-8077-4ed4-9947-ca3e991a253f"
  fi

  # Get Azure AD Tenant Id for AKS admin access
  if [ -z "$k8sRbacEntraProfileTenantId" ]; then
    azd env set k8sRbacEntraProfileTenantId "cdbba3b9-3344-40cd-9f2d-5a463efc272d"
    log_info "Set AD Tenant for AKS admin Access to cdbba3b9-3344-40cd-9f2d-5a463efc272d"
  fi

  # Set other required environment variables if not already set
  if [ -z "$location" ]; then
    azd env set location "eastus2"
    log_info "Set default location to eastus2"
  fi

  if [ -z "$environmentName" ]; then
    azd env set environmentName "dev"
    log_info "Set environment name to dev"
  fi

  if [ -z "$domainName" ]; then
    azd env set domainName "fabrikam.com"
    log_info "Set default domain name to fabrikam.com"
  fi

  if [ -z "$kubernetesVersion" ]; then
    azd env set kubernetesVersion "1.30.12"
    log_info "Set Kubernetes version to 1.30.12"
  fi

  # Generated by Copilot - Set current user object ID for Key Vault permissions
  if [ -z "$(azd env get-value currentUserObjectId 2>/dev/null)" ]; then
    local current_user_oid=$(az ad signed-in-user show --query id --output tsv 2>/dev/null || echo "")
    if [ -n "$current_user_oid" ]; then
      azd env set currentUserObjectId "$current_user_oid"
      log_info "Set current user object ID for Key Vault access: $current_user_oid"
    else
      log_warning "Could not retrieve current user object ID - Key Vault permissions will be set in post-provisioning"
    fi
  fi

  log_success "Environment variables configured"
}

# Validate resource naming
validate_naming() {
  log_info "Validating resource naming conventions..."

  # Check if names will be unique enough
  SUBSCRIPTION_ID=$azureSubscriptionId
  ENV_NAME=$environmentName
  LOCATION=location

  UNIQUE_ID=$(echo "$SUBSCRIPTION_ID-$LOCATION-$ENV_NAME" | sha256sum | cut -c1-10)

  # Test some critical resource names
  TEST_ACR_NAME="acr${UNIQUE_ID}"
  TEST_KV_NAME="kv-${UNIQUE_ID}"

  # Check if ACR name is available (basic format check)
  if [ ${#TEST_ACR_NAME} -gt 50 ]; then
    log_error "Generated ACR name '$TEST_ACR_NAME' is too long"
    exit 1
  fi

  # Check if Key Vault name is available (basic format check)
  if [ ${#TEST_KV_NAME} -gt 24 ]; then
    log_error "Generated Key Vault name '$TEST_KV_NAME' is too long"
    exit 1
  fi

  log_success "Resource naming validation completed"
}

# Enable required Azure resource providers
enable_resource_providers() {
  log_info "Enabling required Azure resource providers..."

  PROVIDERS=(
    "Microsoft.ContainerService"
    "Microsoft.ContainerRegistry"
    "Microsoft.Network"
    "Microsoft.ManagedIdentity"
    "Microsoft.KeyVault"
    "Microsoft.DocumentDB"
    "Microsoft.Cache"
    "Microsoft.ServiceBus"
    "Microsoft.Insights"
    "Microsoft.OperationalInsights"
    "Microsoft.Authorization"
  )

  for provider in "${PROVIDERS[@]}"; do
    log_info "Registering provider: $provider"
    az provider register --namespace "$provider" --wait
  done

  log_success "Resource providers enabled"
}

# Generated by Copilot - TLS Certificate generation following 02-ca-certificates.md
generate_tls_certificates() {
  log_info "Generating TLS certificates following 02-ca-certificates.md procedures..."

  # Create certificates directory
  local cert_dir="./certificates"
  mkdir -p "$cert_dir"
  cd "$cert_dir"

  # Check if openssl is available
  if ! command -v openssl &>/dev/null; then
    log_error "OpenSSL is not installed. Please install it first."
    exit 1
  fi

  # 1. Generate a client-facing self-signed TLS certificate for Azure Application Gateway
  log_info "Generating client-facing certificate for dronedelivery.fabrikam.com..."

  if [ ! -f "appgw.crt" ] || [ ! -f "appgw.key" ]; then
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -out appgw.crt \
      -keyout appgw.key \
      -subj "/CN=dronedelivery.fabrikam.com/O=Fabrikam Drone Delivery"

    if [ $? -eq 0 ]; then
      log_success "Application Gateway certificate generated: appgw.crt"
    else
      log_error "Failed to generate Application Gateway certificate"
      exit 1
    fi
  else
    log_info "Application Gateway certificate already exists, skipping generation"
  fi

  # Convert to PFX format for Key Vault storage
  log_info "Converting certificate to PFX format..."

  if [ ! -f "appgw.pfx" ]; then
    openssl pkcs12 -export -out appgw.pfx \
      -in appgw.crt \
      -inkey appgw.key \
      -passout pass:

    if [ $? -eq 0 ]; then
      log_success "PFX certificate created: appgw.pfx"
    else
      log_error "Failed to create PFX certificate"
      exit 1
    fi
  else
    log_info "PFX certificate already exists, skipping conversion"
  fi

  # 2. Base64 encode the client-facing certificate
  log_info "Base64 encoding Application Gateway certificate..."

  if [ -f "appgw.pfx" ]; then
    export APP_GATEWAY_LISTENER_CERTIFICATE=$(cat appgw.pfx | base64 | tr -d '\n')

    # Set in azd environment
    azd env set APP_GATEWAY_LISTENER_CERTIFICATE "$APP_GATEWAY_LISTENER_CERTIFICATE"
    log_success "Application Gateway certificate base64 encoded and stored in azd env"
  else
    log_error "appgw.pfx not found, cannot encode"
    exit 1
  fi

  # 3. Generate the wildcard certificate for the AKS Ingress Controller
  log_info "Generating wildcard certificate for *.aks-agic.fabrikam.com..."

  if [ ! -f "k8sic.crt" ] || [ ! -f "k8sic.key" ]; then
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -out k8sic.crt \
      -keyout k8sic.key \
      -subj "/CN=*.aks-agic.fabrikam.com/O=Fabrikam Aks Ingress"

    if [ $? -eq 0 ]; then
      log_success "AKS Ingress Controller certificate generated: k8sic.crt"
    else
      log_error "Failed to generate AKS Ingress Controller certificate"
      exit 1
    fi
  else
    log_info "AKS Ingress Controller certificate already exists, skipping generation"
  fi

  # 4. Base64 encode the AKS Ingress Controller certificate
  log_info "Base64 encoding AKS Ingress Controller certificate..."

  if [ -f "k8sic.crt" ]; then
    export AKS_INGRESS_CONTROLLER_CERTIFICATE_BASE64=$(cat k8sic.crt | base64 | tr -d '\n')

    # Set in azd environment
    azd env set AKS_INGRESS_CONTROLLER_CERTIFICATE_BASE64 "$AKS_INGRESS_CONTROLLER_CERTIFICATE_BASE64"
    log_success "AKS Ingress Controller certificate base64 encoded and stored in azd env"
  else
    log_error "k8sic.crt not found, cannot encode"
    exit 1
  fi

  # Return to original directory
  cd ..

  # Validate generated certificates
  validate_certificates "$cert_dir"

  log_success "TLS certificates generation completed successfully!"

  # Display warning about self-signed certificates
  echo ""
  log_warning "⚠️  IMPORTANT SECURITY NOTICE ⚠️"
  log_warning "These are self-signed certificates for development/testing only!"
  log_warning "DO NOT use these certificates in production environments!"
  log_warning "For production, procure certificates from a trusted CA."
  echo ""
}

# Generated by Copilot - Validate generated certificates
validate_certificates() {
  local cert_dir="$1"
  log_info "Validating generated certificates..."

  # Validate Application Gateway certificate
  if [ -f "$cert_dir/appgw.crt" ]; then
    local app_gw_cn=$(openssl x509 -in "$cert_dir/appgw.crt" -noout -subject | sed -n 's/.*CN[[:space:]]*=[[:space:]]*\([^,]*\).*/\1/p')
    if [ "$app_gw_cn" = "dronedelivery.fabrikam.com" ]; then
      log_success "Application Gateway certificate CN validated: $app_gw_cn"
    else
      log_error "Application Gateway certificate CN mismatch: expected 'dronedelivery.fabrikam.com', got '$app_gw_cn'"
      exit 1
    fi
  fi

  # Validate AKS Ingress Controller certificate
  if [ -f "$cert_dir/k8sic.crt" ]; then
    local ingress_cn=$(openssl x509 -in "$cert_dir/k8sic.crt" -noout -subject | sed -n 's/.*CN[[:space:]]*=[[:space:]]*\([^,]*\).*/\1/p')
    if [ "$ingress_cn" = "*.aks-agic.fabrikam.com" ]; then
      log_success "AKS Ingress Controller certificate CN validated: $ingress_cn"
    else
      log_error "AKS Ingress Controller certificate CN mismatch: expected '*.aks-agic.fabrikam.com', got '$ingress_cn'"
      exit 1
    fi
  fi

  # Check certificate validity periods
  log_info "Certificate validity information:"
  if [ -f "$cert_dir/appgw.crt" ]; then
    local app_gw_validity=$(openssl x509 -in "$cert_dir/appgw.crt" -noout -dates)
    log_info "Application Gateway cert: $app_gw_validity"
  fi

  if [ -f "$cert_dir/k8sic.crt" ]; then
    local ingress_validity=$(openssl x509 -in "$cert_dir/k8sic.crt" -noout -dates)
    log_info "AKS Ingress Controller cert: $ingress_validity"
  fi

  log_success "Certificate validation completed"
}

# Generated by Copilot - Display certificate information
display_certificate_summary() {
  log_info "Certificate Generation Summary:"
  echo ""
  echo "📁 Generated files in ./certificates/:"
  echo "   ├── appgw.crt     (Application Gateway public certificate)"
  echo "   ├── appgw.key     (Application Gateway private key)"
  echo "   ├── appgw.pfx     (Application Gateway PKCS#12 bundle)"
  echo "   ├── k8sic.crt     (AKS Ingress Controller public certificate)"
  echo "   └── k8sic.key     (AKS Ingress Controller private key)"
  echo ""
  echo "🔐 Environment variables set:"
  echo "   ├── APP_GATEWAY_LISTENER_CERTIFICATE (Base64 PFX for Key Vault)"
  echo "   └── AKS_INGRESS_CONTROLLER_CERTIFICATE_BASE64 (Base64 CRT for K8s)"
  echo ""
  echo "🎯 Certificate details:"
  echo "   ├── Application Gateway: dronedelivery.fabrikam.com"
  echo "   ├── AKS Ingress Controller: *.aks-agic.fabrikam.com"
  echo "   ├── Validity: 365 days"
  echo "   └── Key size: RSA 2048 bits"
  echo ""
}

# Main execution
main() {
  echo ""
  echo "=================================================="
  echo "  🚀 Fabrikam Drone Delivery Pre-Provisioning"
  echo "=================================================="
  echo ""

  check_prerequisites
  validate_permissions
  enable_resource_providers
  check_environment_variables
  validate_naming
  generate_tls_certificates
  display_certificate_summary

  echo ""
  log_success "Pre-provisioning setup completed successfully!"
  echo ""
  log_info "Next step: Run 'azd provision' to deploy infrastructure"
  echo ""
}

# Run main function
main "$@"
