// Generated by Copilot
// Container Registry module for Azure Container Registry (ACR)
targetScope = 'resourceGroup'

// ============================================================================
// PARAMETERS
// ============================================================================

@description('Primary deployment location')
param location string = resourceGroup().location
@description('Resource prefix identifier for resource naming')
param resourceSuffix string
@description('Unique identifier for resource naming')
param acrSku string
@description('Spoke Node Pool Subnet Prefix')
param vnetNodePoolSubnetResourceId string
@description('Private Dns Zone para AKV')
param acrPrivateDnsZone string
@description('Log Analitics Workspace Id')
param logAnalyticsWorkspaceId string
@description('Log Analitics Resource log configuration')
param logConfigurations object
@description('Log Analitics Resource metrics configuration')
param metricsConfiguration array
@description('Resource tags')
param tags object = {}

// ============================================================================
// VARIABLES
// ============================================================================

var acrName = 'acrreg${resourceSuffix}'
// var acrSku = 'Premium' // Using Premium SKU for region compatibility

// ============================================================================
// CONTAINER REGISTRY
// ============================================================================

resource containerRegistry 'Microsoft.ContainerRegistry/registries@2023-07-01' = {
  name: acrName
  location: location
  tags: tags
  sku: {
    name: acrSku
  }
  properties: {
    adminUserEnabled: false
    // Network rules only for Premium SKU
    networkRuleSet: {
      defaultAction: 'Allow'
      ipRules: []
    }
    policies: {
      quarantinePolicy: {
        status: 'enabled'
      }
      trustPolicy: {
        type: 'Notary'
        status: 'enabled' // Trust policy supported in Premium SKU
      }
      retentionPolicy: {
        days: 30
        status: 'enabled' // Retention policy supported in Premium SKU
      }
    }
    encryption: {
      status: 'disabled'
    }
    dataEndpointEnabled: false
    publicNetworkAccess: 'Enabled'
    // Zone redundancy only supported for Premium SKU
  }
}
// ============================================================================
// PRIVATE LINK ENDPOINT
// ============================================================================
resource nodepoolToAkvPrivateEndpoint 'Microsoft.Network/privateEndpoints@2023-04-01' = {
  name: 'nodepool-to-acr'
  location: location
  properties: {
    subnet: {
      id: vnetNodePoolSubnetResourceId
    }
    privateLinkServiceConnections: [
      {
        name: 'nodepoolsubnet-to-registry'
        properties: {
          privateLinkServiceId: containerRegistry.id
          groupIds: [
            'registry'
          ]
        }
      }
    ]
  }
}
resource nodepoolToAcrPrivateEndpointDNSGroup 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2023-04-01' = {
  parent: nodepoolToAkvPrivateEndpoint
  name: 'default'
  properties: {
    privateDnsZoneConfigs: [
      {
        name: 'privatelink-acr-net'
        properties: {
          privateDnsZoneId: acrPrivateDnsZone
        }
      }
    ]
  }
}
// ============================================================================
// OBSERVABILITY
// ============================================================================
resource firewallDiagnosticSetting 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'diagSettings-${acrName}'
  scope: containerRegistry
  properties: {
    workspaceId: logAnalyticsWorkspaceId
    logs: logConfigurations.acrPremium
    metrics: metricsConfiguration
  }
}
// ============================================================================
// OUTPUTS
// ============================================================================

output registryId string = containerRegistry.id
output registryName string = containerRegistry.name
output registryLoginServer string = containerRegistry.properties.loginServer
output registryResourceGroup string = resourceGroup().name
