// Generated by Copilot
// Security module - Key Vault, Managed Identities, and Certificate management
targetScope = 'resourceGroup'

// ============================================================================
// PARAMETERS
// ============================================================================
@description('Primary deployment location')
param location string
@description('Resource prefix identifier for resource naming')
param resourceSuffix string
@description('Domain name for certificate generation')
param domainName string
@description('Tenant Id')
@secure()
param azureTenantId string
@description('Resource tags')
param tags object = { what: 'rbac' }
// Object ID of the current user or service principal for Key Vault access
@description('Object ID of the current user or service principal for Key Vault access')
param currentUserObjectId string = ''
// Object ID of the AKS cluster managed identity
@description('Object ID of the AKS cluster managed identity')
param aksClusterIdentityObjectId string = ''
@description('Spoke Node Pool Subnet Prefix')
param vnetNodePoolSubnetResourceId string
@description('Private Dns Zone para AKV')
param akvPrivateDnsZone string
@description('Log Analitics Workspace Id')
param logAnalyticsWorkspaceId string
@description('Log Analitics Resource log configuration')
param logConfigurations object
@description('Log Analitics Resource metrics configuration')
param metricsConfiguration array
// ============================================================================
// VARIABLES
// ============================================================================
var deliveryKeyVaultName = 'kv-delivery-${resourceSuffix}'
var packageyKeyVaultName = 'kv-package-${resourceSuffix}'
var ingestionKeyVaultName = 'kv-ingestion-${resourceSuffix}'
var droneSchedulerKeyVaultName = 'kv-schedule-${resourceSuffix}'
var workflowKeyVaultName = 'kv-workflow-${resourceSuffix}'
var computeKeyVaultName = 'kv-compute-${resourceSuffix}'
var keyVaultSecretsUserRole = subscriptionResourceId(
  'Microsoft.Authorization/roleDefinitions',
  '4633458b-17de-408a-b874-0445c86b69e6'
)
var keyVaultCertificateUserRole = subscriptionResourceId(
  'Microsoft.Authorization/roleDefinitions',
  'db79e9a7-68ee-4b58-9aeb-b90e7c24fcba'
)
var keyVaultCertificateOfficerRole = subscriptionResourceId(
  'Microsoft.Authorization/roleDefinitions',
  'a4417e6f-fecd-4de8-b567-7b0420556985'
)
var keyVaultSecretsOfficerRole = subscriptionResourceId(
  'Microsoft.Authorization/roleDefinitions',
  'b86a8fe4-44ce-4948-aee5-eccb2c155cd7'
)
var keyVaultCryptoOfficerRole = subscriptionResourceId(
  'Microsoft.Authorization/roleDefinitions',
  '14b46e9e-c2b7-41b4-b07b-48a6ebf60603'
)
// Managed Identity names for each microservice
var managedIdentityNames = {
  package: 'uid-package-${resourceSuffix}'
  delivery: 'uid-delivery-${resourceSuffix}'
  ingestion: 'uid-ingestion-${resourceSuffix}'
  dronescheduler: 'uid-dronescheduler-${resourceSuffix}'
  workflow: 'uid-workflow-${resourceSuffix}'
  ingressController: 'uid-ingress-${resourceSuffix}'
  applicationGateway: 'uid-appgw-${resourceSuffix}'
}
// ============================================================================
// KEY VAULT
// ============================================================================
resource packageKeyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: packageyKeyVaultName
  location: location
  tags: {
    displayName: 'Package Key Vault'
    app: 'fabrikam-package'
  }
  properties: {
    sku: {
      family: 'A'
      name: 'standard'
    }
    tenantId: azureTenantId
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Allow'
      virtualNetworkRules: []
      ipRules: []
    }
    accessPolicies: []
    enableRbacAuthorization: true
    enabledForDeployment: true
    enabledForTemplateDeployment: true
    enabledForDiskEncryption: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 7
    // enablePurgeProtection: false // Enable purge protection for security
  }
}
resource deliveryKeyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: deliveryKeyVaultName
  location: location
  tags: {
    displayName: 'Package Key Vault'
    app: 'fabrikam-package'
  }
  properties: {
    sku: {
      family: 'A'
      name: 'standard'
    }
    tenantId: azureTenantId
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Allow'
      virtualNetworkRules: []
      ipRules: []
    }
    accessPolicies: []
    enableRbacAuthorization: true
    enabledForDeployment: true
    enabledForTemplateDeployment: true
    enabledForDiskEncryption: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 7
  }
}
resource ingestionKeyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: ingestionKeyVaultName
  location: location
  tags: {
    displayName: 'Package Key Vault'
    app: 'fabrikam-package'
  }
  properties: {
    sku: {
      family: 'A'
      name: 'standard'
    }
    tenantId: azureTenantId
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Allow'
      virtualNetworkRules: []
      ipRules: []
    }
    accessPolicies: []
    enableRbacAuthorization: true
    enabledForDeployment: true
    enabledForTemplateDeployment: true
    enabledForDiskEncryption: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 7
  }
}
resource droneSchedulerKeyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: droneSchedulerKeyVaultName
  location: location
  tags: {
    displayName: 'Package Key Vault'
    app: 'fabrikam-package'
  }
  properties: {
    sku: {
      family: 'A'
      name: 'standard'
    }
    tenantId: azureTenantId
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Allow'
      virtualNetworkRules: []
      ipRules: []
    }
    accessPolicies: []
    enableRbacAuthorization: true
    enabledForDeployment: true
    enabledForTemplateDeployment: true
    enabledForDiskEncryption: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 7
  }
}
resource computeKeyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: computeKeyVaultName
  location: location
  tags: {
    displayName: 'Compute Key Vault'
    what: 'AppGW and Ingress Vault'
  }
  properties: {
    sku: {
      family: 'A'
      name: 'standard'
    }
    tenantId: azureTenantId
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Allow'
      virtualNetworkRules: []
      ipRules: []
    }
    accessPolicies: []
    enableRbacAuthorization: true
    enabledForDeployment: true
    enabledForTemplateDeployment: true
    enabledForDiskEncryption: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 7
  }
}
resource workflowKeyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: workflowKeyVaultName
  location: location
  tags: {
    displayName: 'Package Key Vault'
    app: 'fabrikam-package'
  }
  properties: {
    sku: {
      family: 'A'
      name: 'standard'
    }
    tenantId: azureTenantId
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Allow'
      virtualNetworkRules: []
      ipRules: []
    }
    accessPolicies: []
    enableRbacAuthorization: true
    enabledForDeployment: true
    enabledForTemplateDeployment: true
    enabledForDiskEncryption: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 7
  }
}
// ============================================================================
// MANAGED IDENTITIES
// ============================================================================
resource packageManagedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: managedIdentityNames.package
  location: location
  tags: union(tags, { Service: 'package', reason: 'aad-workload-identity' })
}
resource deliveryManagedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: managedIdentityNames.delivery
  location: location
  tags: union(tags, { Service: 'delivery', reason: 'aad-workload-identity' })
}
resource ingestionManagedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: managedIdentityNames.ingestion
  location: location
  tags: union(tags, { Service: 'ingestion', reason: 'aad-workload-identity' })
}
resource droneschedulerManagedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: managedIdentityNames.dronescheduler
  location: location
  tags: union(tags, { Service: 'dronescheduler', reason: 'aad-workload-identity' })
}
resource workflowManagedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: managedIdentityNames.workflow
  location: location
  tags: union(tags, { Service: 'workflow', reason: 'aad-workload-identity' })
}
resource ingressControllerManagedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: managedIdentityNames.ingressController
  location: location
  tags: union(tags, { Service: 'ingress-controller' })
}
resource applicationGatewayManagedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: managedIdentityNames.applicationGateway
  location: location
  tags: union(tags, { Service: 'application-gateway', reason: 'aad-pod-identity' })
}
// ============================================================================
// KEY VAULT RBAC ASSIGNMENTS
// ============================================================================
// Micro Services access to Key Vault secrets
resource packageKeyVaultSecretsUserRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: packageKeyVault
  name: guid(packageManagedIdentity.id, packageKeyVault.id, keyVaultSecretsUserRole)
  properties: {
    roleDefinitionId: keyVaultSecretsUserRole
    principalId: packageManagedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}
// Delivery service access to Key Vault secrets
resource deliveryKeyVaultSecretsUserRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: deliveryKeyVault
  name: guid(deliveryManagedIdentity.id, deliveryKeyVault.id, keyVaultSecretsUserRole)
  properties: {
    roleDefinitionId: keyVaultSecretsUserRole
    principalId: deliveryManagedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}
// Ingestion service access to Key Vault secrets
resource ingestionKeyVaultSecretsUserRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: ingestionKeyVault
  name: guid(ingestionManagedIdentity.id, ingestionKeyVault.id, keyVaultSecretsUserRole)
  properties: {
    roleDefinitionId: keyVaultSecretsUserRole
    principalId: ingestionManagedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}
// DroneScheduler service access to Key Vault secrets
resource droneschedulerKeyVaultSecretsUserRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: droneSchedulerKeyVault
  name: guid(droneschedulerManagedIdentity.id, droneSchedulerKeyVault.id, keyVaultSecretsUserRole)
  properties: {
    roleDefinitionId: keyVaultSecretsUserRole
    principalId: droneschedulerManagedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}
// Workflow service access to Key Vault secrets
resource workflowKeyVaultSecretsUserRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: workflowKeyVault
  name: guid(workflowManagedIdentity.id, workflowKeyVault.id, keyVaultSecretsUserRole)
  properties: {
    roleDefinitionId: keyVaultSecretsUserRole
    principalId: workflowManagedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}
// Ingress Controller access to Key Vault certificates
resource ingressControllerKeyVaultCertificateUserRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: computeKeyVault
  name: guid(ingressControllerManagedIdentity.id, computeKeyVault.id, keyVaultCertificateUserRole)
  properties: {
    roleDefinitionId: keyVaultCertificateUserRole
    principalId: ingressControllerManagedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}
// Application Gateway access to Key Vault certificates
resource applicationGatewayKeyVaultSecretsUserRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: computeKeyVault
  name: guid(applicationGatewayManagedIdentity.id, computeKeyVault.id, keyVaultSecretsUserRole)
  properties: {
    roleDefinitionId: keyVaultSecretsUserRole
    principalId: applicationGatewayManagedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}
// Role assignments for AKS cluster managed identity
resource aksClusterKeyVaultSecretsUserRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (!empty(aksClusterIdentityObjectId)) {
  scope: computeKeyVault
  name: guid(aksClusterIdentityObjectId, computeKeyVault.id, keyVaultSecretsUserRole)
  properties: {
    roleDefinitionId: keyVaultSecretsUserRole
    principalId: aksClusterIdentityObjectId
    principalType: 'ServicePrincipal'
  }
}
// ============================================================================
// CERTIFICATES (Placeholder - will be created by post-deployment scripts)
// ============================================================================
// Note: Self-signed certificates will be generated and stored by the post-deployment hook
// This ensures the certificates are available for Application Gateway and Ingress Controller
// Generated by Copilot - Additional Key Vault RBAC assignments for certificate management
// Application Gateway Certificate Officer role for certificate import
resource applicationGatewayKeyVaultCertificateOfficerRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: computeKeyVault
  name: guid(applicationGatewayManagedIdentity.id, computeKeyVault.id, keyVaultCertificateOfficerRole)
  properties: {
    roleDefinitionId: keyVaultCertificateOfficerRole
    principalId: applicationGatewayManagedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}
// Ingress Controller Certificate Officer role for certificate import
resource ingressControllerKeyVaultCertificateOfficerRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: computeKeyVault
  name: guid(ingressControllerManagedIdentity.id, computeKeyVault.id, keyVaultCertificateOfficerRole)
  properties: {
    roleDefinitionId: keyVaultCertificateOfficerRole
    principalId: ingressControllerManagedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}
// Generated by Copilot - Secrets Officer roles for sensitive operations
resource deliveryKeyVaultSecretsOfficerRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: computeKeyVault
  name: guid(deliveryManagedIdentity.id, computeKeyVault.id, keyVaultSecretsOfficerRole)
  properties: {
    roleDefinitionId: keyVaultSecretsOfficerRole
    principalId: deliveryManagedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}
resource ingestionKeyVaultSecretsOfficerRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: computeKeyVault
  name: guid(ingestionManagedIdentity.id, computeKeyVault.id, keyVaultSecretsOfficerRole)
  properties: {
    roleDefinitionId: keyVaultSecretsOfficerRole
    principalId: ingestionManagedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}
// Generated by Copilot - Crypto Officer roles for encryption operations
resource applicationGatewayCryptoOfficerRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: computeKeyVault
  name: guid(applicationGatewayManagedIdentity.id, computeKeyVault.id, keyVaultCryptoOfficerRole)
  properties: {
    roleDefinitionId: keyVaultCryptoOfficerRole
    principalId: applicationGatewayManagedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}
resource ingressControllerCryptoOfficerRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: computeKeyVault
  name: guid(ingressControllerManagedIdentity.id, computeKeyVault.id, keyVaultCryptoOfficerRole)
  properties: {
    roleDefinitionId: keyVaultCryptoOfficerRole
    principalId: ingressControllerManagedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}
// Generated by Copilot - Role assignments for current user (for post-provisioning operations)
resource currentUserKeyVaultCertificateOfficerRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (!empty(currentUserObjectId)) {
  scope: computeKeyVault
  name: guid(currentUserObjectId, computeKeyVault.id, keyVaultCertificateOfficerRole)
  properties: {
    roleDefinitionId: keyVaultCertificateOfficerRole
    principalId: currentUserObjectId
    principalType: 'User'
  }
}
resource currentUserKeyVaultSecretsOfficerRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (!empty(currentUserObjectId)) {
  scope: computeKeyVault
  name: guid(currentUserObjectId, computeKeyVault.id, keyVaultSecretsOfficerRole)
  properties: {
    roleDefinitionId: keyVaultSecretsOfficerRole
    principalId: currentUserObjectId
    principalType: 'User'
  }
}

resource aksClusterKeyVaultCertificateUserRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (!empty(aksClusterIdentityObjectId)) {
  scope: computeKeyVault
  name: guid(aksClusterIdentityObjectId, computeKeyVault.id, keyVaultCertificateUserRole)
  properties: {
    roleDefinitionId: keyVaultCertificateUserRole
    principalId: aksClusterIdentityObjectId
    principalType: 'ServicePrincipal'
  }
}
// ============================================================================
// PRIVATE LINK ENDPOINT
// ============================================================================
resource nodepoolToAkvPrivateEndpoint 'Microsoft.Network/privateEndpoints@2023-04-01' = {
  name: 'nodepool-to-akv'
  location: location
  properties: {
    subnet: {
      id: vnetNodePoolSubnetResourceId
    }
    privateLinkServiceConnections: [
      {
        name: 'nodepoolsubnet-to-akv'
        properties: {
          privateLinkServiceId: computeKeyVault.id
          groupIds: [
            'vault'
          ]
        }
      }
    ]
  }
}
resource nodepoolToAkvPrivateEndpointDNSGroup 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2023-04-01' = {
  parent: nodepoolToAkvPrivateEndpoint
  name: 'default'
  properties: {
    privateDnsZoneConfigs: [
      {
        name: 'privatelink-akv-net'
        properties: {
          privateDnsZoneId: akvPrivateDnsZone
        }
      }
    ]
  }
}
// ============================================================================
// OBSERVABILITY
// ============================================================================
resource DiagnosticSettingPackageKeyVault 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'diagSettings-${packageyKeyVaultName}'
  scope: packageKeyVault
  properties: {
    workspaceId: logAnalyticsWorkspaceId
    logs: logConfigurations.keyVault
    metrics: metricsConfiguration
  }
}
resource DiagnosticSettingDeliveryKeyVault 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'diagSettings-${deliveryKeyVaultName}'
  scope: deliveryKeyVault
  properties: {
    workspaceId: logAnalyticsWorkspaceId
    logs: logConfigurations.keyVault
    metrics: metricsConfiguration
  }
}
resource DiagnosticSettingIngestionKeyVault 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'diagSettings-${ingestionKeyVaultName}'
  scope: ingestionKeyVault
  properties: {
    workspaceId: logAnalyticsWorkspaceId
    logs: logConfigurations.keyVault
    metrics: metricsConfiguration
  }
}
resource DiagnosticSettingDroneSchedulerKeyVault 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'diagSettings-${droneSchedulerKeyVaultName}'
  scope: droneSchedulerKeyVault
  properties: {
    workspaceId: logAnalyticsWorkspaceId
    logs: logConfigurations.keyVault
    metrics: metricsConfiguration
  }
}
resource DiagnosticSettingWorkflowKeyVault 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'diagSettings-${workflowKeyVaultName}'
  scope: workflowKeyVault
  properties: {
    workspaceId: logAnalyticsWorkspaceId
    logs: logConfigurations.keyVault
    metrics: metricsConfiguration
  }
}
// ============================================================================
// OUTPUTS
// ============================================================================
output keyVaultPackageId string = packageKeyVault.id
output keyVaultPackageName string = packageKeyVault.name
output keyVaultPackagetUri string = packageKeyVault.properties.vaultUri
output keyVaultDeliveryId string = deliveryKeyVault.id
output keyVaultDeliveryName string = deliveryKeyVault.name
output keyVaultDeliveryUri string = deliveryKeyVault.properties.vaultUri
output keyVaultIngestionId string = ingestionKeyVault.id
output keyVaultIngestionName string = ingestionKeyVault.name
output keyVaultIngestiontUri string = ingestionKeyVault.properties.vaultUri
output keyVaultDroneSchedulerId string = droneSchedulerKeyVault.id
output keyVaultDroneSchedulerName string = droneSchedulerKeyVault.name
output keyVaultDroneSchedulerUri string = droneSchedulerKeyVault.properties.vaultUri
output keyVaultWorkflowId string = workflowKeyVault.id
output keyVaultWorkflowName string = workflowKeyVault.name
output keyVaultWorkflowUri string = workflowKeyVault.properties.vaultUri
output keyVaultComputeId string = computeKeyVault.id
output keyVaultComputeName string = computeKeyVault.name
output keyVaultComputeUri string = computeKeyVault.properties.vaultUri
// Managed Identity outputs
output managedIdentities object = {
  delivery: {
    id: deliveryManagedIdentity.id
    name: deliveryManagedIdentity.name
    clientId: deliveryManagedIdentity.properties.clientId
    principalId: deliveryManagedIdentity.properties.principalId
  }
  ingestion: {
    id: ingestionManagedIdentity.id
    name: ingestionManagedIdentity.name
    clientId: ingestionManagedIdentity.properties.clientId
    principalId: ingestionManagedIdentity.properties.principalId
  }
  workflow: {
    id: workflowManagedIdentity.id
    name: workflowManagedIdentity.name
    clientId: workflowManagedIdentity.properties.clientId
    principalId: workflowManagedIdentity.properties.principalId
  }
  dronescheduler: {
    id: droneschedulerManagedIdentity.id
    name: droneschedulerManagedIdentity.name
    clientId: droneschedulerManagedIdentity.properties.clientId
    principalId: droneschedulerManagedIdentity.properties.principalId
  }
  package: {
    id: packageManagedIdentity.id
    name: packageManagedIdentity.name
    clientId: packageManagedIdentity.properties.clientId
    principalId: packageManagedIdentity.properties.principalId
  }
  ingressController: {
    id: ingressControllerManagedIdentity.id
    name: ingressControllerManagedIdentity.name
    clientId: ingressControllerManagedIdentity.properties.clientId
    principalId: ingressControllerManagedIdentity.properties.principalId
  }
  applicationGateway: {
    id: applicationGatewayManagedIdentity.id
    name: applicationGatewayManagedIdentity.name
    clientId: applicationGatewayManagedIdentity.properties.clientId
    principalId: applicationGatewayManagedIdentity.properties.principalId
  }
}
