#!/bin/bash
# Generated by Copilot
# Script simples para gerenciar variáveis azd

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}ℹ️  $1${NC}"; }
log_success() { echo -e "${GREEN}✅ $1${NC}"; }
log_warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }
log_error() { echo -e "${RED}❌ $1${NC}"; }
log_header() { echo -e "${CYAN}$1${NC}"; }

echo ""
log_header "=================================================="
log_header "  🚀 Gerenciador de Variáveis Azure Developer CLI"
log_header "=================================================="
echo ""

# Verifica azd
if ! command -v azd &> /dev/null; then
    log_error "Azure Developer CLI (azd) não está instalado!"
    exit 1
fi

# Mostra ambiente atual
current_env=$(azd env list | grep "true" | awk '{print $1}' | head -1)
log_info "Ambiente ativo: $current_env"
echo ""

# Função para listar variáveis
list_vars() {
    log_header "=== Variáveis Existentes ==="
    azd env get-values | while IFS='=' read -r key value; do
        clean_value=$(echo "$value" | sed 's/^"//;s/"$//')
        printf "  %-35s = %s\n" "$key" "$clean_value"
    done
    echo ""
}

# Função para definir variável
set_var() {
    local var_name="$1"
    local var_value="$2"
    
    if azd env set "$var_name" "$var_value"; then
        log_success "Variável '$var_name' definida com sucesso!"
        return 0
    else
        log_error "Erro ao definir a variável '$var_name'"
        return 1
    fi
}

# Menu interativo
while true; do
    echo ""
    log_header "=== Opções ==="
    echo "1. Listar variáveis existentes"
    echo "2. Definir nova variável"
    echo "3. Preset Fabrikam (variáveis padrão)"
    echo "4. Sair"
    echo ""
    
    read -p "Escolha uma opção (1-4): " opcao
    
    case $opcao in
        1)
            list_vars
            ;;
        2)
            echo ""
            read -p "Nome da variável: " var_name
            read -p "Valor da variável: " var_value
            
            if [ -n "$var_name" ] && [ -n "$var_value" ]; then
                set_var "$var_name" "$var_value"
            else
                log_warning "Nome e valor não podem estar vazios!"
            fi
            ;;
        3)
            echo ""
            log_header "=== Configurando Preset Fabrikam ==="
            
            # Variáveis específicas do projeto
            declare -a preset_vars=(
                "DOMAIN_NAME=fabrikam.com"
                "ENVIRONMENT_NAME=dev"
                "KUBERNETES_VERSION=1.30.12"
            )
            
            log_info "Configurando variáveis padrão do projeto..."
            
            for var in "${preset_vars[@]}"; do
                IFS='=' read -r name value <<< "$var"
                echo "Definindo: $name = $value"
                set_var "$name" "$value"
            done
            
            log_success "Preset configurado!"
            ;;
        4)
            log_success "Saindo..."
            break
            ;;
        *)
            log_warning "Opção inválida! Escolha entre 1-4."
            ;;
    esac
done
