#!/bin/zsh
# Generated by Copilot
# Script simples para definir variáveis azd - otimizado para zsh
if [ -z "$ZSH_VERSION" ]; then
    echo -e "${YELLOW}⚠️ Este script foi otimizado para Zsh, mas pode funcionar em outras shells.${NC}"
fi
if ! command -v azd &> /dev/null; then
    echo -e "${RED}❌ O Azure Developer CLI (azd) não está instalado!${NC}"
    exit 1
fi
# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}🚀 Configurador de Variáveis AZD${NC}"
echo ""

# Mostra variáveis atuais
echo -e "${BLUE}📋 Variáveis atuais:${NC}"
azd env get-values
echo ""

#carrega um ambiente especifico (dev, hml,prd)
environmentName=$(azd env get-values | grep "environmentName=" | cut -d '=' -f2 | tr -d '"')
if [[ -z "$environmentName" ]]; then
    echo -e "${RED}❌ Variável environmentName não definida no azd!${NC}"
    exit 1
fi
envFile="infra/preset/.env.$environmentName"
if [[ ! -f "$envFile" ]]; then
    echo -e "${RED}❌ Arquivo .env não encontrado: $envFile${NC}"
    exit 1
else
    source "$envFile"
    echo -e "${GREEN}✅ Arquivo .env carregado!${NC}"
fi

# Função para definir variáveis
set_variable() {
    local name=$1
    local value=$2    
    if azd env set "$name" "$value"; then
        echo -e "${GREEN}✅ $name definida com sucesso!${NC}"
    else
        echo -e "${RED}❌ Erro ao definir $name${NC}"
    fi
}

# Preset para variáveis do Fabrikam
setup_fabrikam_preset() {
    set_variable "location" $AZURE_LOCATION
    set_variable "geoRedundancyLocation" $GEO_REDUNDANCY_LOCATION 
    set_variable "azureTenantId" $AZURE_TENANT_ID
    set_variable "azureSubscriptionId" $AZURE_SUBSCRIPTION_ID
    set_variable "appName" $APP_NAME
    set_variable "domainName" $DOMAIN_NAME
    set_variable "kubernetesVersion" $KUBERNETES_VERSION
    set_variable "k8sRbacEntraProfileTenantId" $K8S_RBAC_ENTRA_PROFILE_TENANT_ID
    set_variable "k8sRbacEntraAdminGroupObjectID" $K8S_RBAC_ENTRA_ADMIN_GROUP_OBJECT_ID
    
    echo -e "${GREEN}✅ Preset configurado!${NC}"
}

make_main_params() {
    local azdEnvValues
    azdEnvValues=$(azd env get-values --output json)
    local paramsFile="infra/main.parameters.json"

    # Garante que o diretório existe e é gravável
    mkdir -p infra

    # Gera o arquivo de parâmetros
    echo '{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {' > "$paramsFile"

    echo "$azdEnvValues" | jq -r 'to_entries | .[] | "    \"" + .key + "\": {\n      \"value\": \"" + .value + "\"\n    },"' >> "$paramsFile"

    # Remove a última vírgula (compatível com Linux e Mac)
    if [[ "$(uname)" == "Darwin" ]]; then
        sed -i '' '$ s/,$//' "$paramsFile"
    else
        sed -i '$ s/,$//' "$paramsFile"
    fi

    echo '  }
}' >> "$paramsFile"

    echo -e "${GREEN}✅ Arquivo main.parameters.json gerado com sucesso!${NC}"
}
# Menu principal
echo "Escolha uma opção:"
echo "1. Definir variável manualmente"
echo "2. Aplicar preset Fabrikam"
echo "3. Gerar Arquivo de Parâmetros Bicep"
echo "4. Sair"

read "opcao?Opção (1-3): "

case $opcao in
    1)
        read "var_name?Nome da variável: "
        read "var_value?Valor da variável: "
        
        if [[ -n "$var_name" && -n "$var_value" ]]; then
            set_variable "$var_name" "$var_value"
        else
            echo -e "${YELLOW}⚠️ Nome e valor são obrigatórios!${NC}"
        fi
        ;;
    2)
        setup_fabrikam_preset
        ;;
    3)
        make_main_params
        ;;      
    4)
        echo -e "${GREEN}👋 Saindo...${NC}"
        exit 0
        ;;
    *)
        echo -e "${RED}❌ Opção inválida!${NC}"
        ;;
esac

echo ""
echo -e "${BLUE}📋 Variáveis após alteração:${NC}"
azd env get-values
