#!/bin/bash
# Generated by Copilot
# Script avançado usando yq para manipulação de YAML

set -euo pipefail

# Cores para output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}🎛️  Gerando kuked config K8s com yq...${NC}"

# Função para instalar yq se necessário
install_yq_if_needed() {
  if ! command -v yq >/dev/null 2>&1; then
    echo -e "${YELLOW}📦 Instalando yq...${NC}"
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
      curl -L "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64" -o /tmp/yq
      sudo mv /tmp/yq /usr/local/bin/yq
      sudo chmod +x /usr/local/bin/yq
    elif [[ "$OSTYPE" == "darwin"* ]]; then
      brew install yq
    else
      echo -e "${RED}❌ Sistema operacional não suportado para instalação automática do yq${NC}"
      exit 1
    fi
    echo -e "${GREEN}✅ yq instalado com sucesso${NC}"
  fi
}
# Carregar configurações
load_environment() {
  # Obter environmentName do azd
  local env_name
  env_name=$(azd env get-values | grep "environmentName=" | cut -d '=' -f2 | tr -d '"')
  if [[ -z "$env_name" ]]; then
    echo -e "${RED}❌ Variável environmentName não definida no azd!${NC}"
    exit 1
  fi
  # Carregar arquivo .env
  local env_file="infra/preset/.env.$env_name"
  if [[ ! -f "$env_file" ]]; then
    echo -e "${RED}❌ Arquivo .env não encontrado: $env_file${NC}"
    exit 1
  fi
  source "$env_file"
  echo -e "${GREEN}✅ Configuração carregada: $env_file${NC}"
  # Processar ACR_NAME
  if [[ -n "$ACR_NAME" ]]; then
    ACR_CLEAN_NAME="${ACR_NAME//-/}"
    ACR_CLEAN_NAME="${ACR_CLEAN_NAME,,}"
    echo -e "${BLUE}📝 ACR: $ACR_NAME -> $ACR_CLEAN_NAME${NC}"
  else
    echo -e "${RED}❌ ACR_NAME não definido${NC}"
    exit 1
  fi
}
# Processar manifesto com yq
process_manifest() {
  local template_file="infra/cluster-manifests/kube-system/kured-1.15.0-dockerhub.template.yaml"
  local output_dir="infra/cluster-manifests/kube-system/generated"
  local output_file="$output_dir/kured-1.15.0-dockerhub.yaml"
  local output_file_generated="infra/cluster-manifests/kube-system/kured-1.15.0-dockerhub.yaml"
  # Verificar template
  if [[ ! -f "$template_file" ]]; then
    echo -e "${RED}❌ Template não encontrado: $template_file${NC}"
    exit 1
  fi
  # Criar diretório
  mkdir -p "$output_dir"
  echo -e "${BLUE}🔄 Processando com yq...${NC}"
  # Generated by Copilot - Processar YAML com yq de forma precisa
  yq eval "
        (.. | select(has(\"image\")) | .image) |= sub(\"\\\${ACR_NAME}\", \"$ACR_CLEAN_NAME\") |
        (.. | select(has(\"name\")) | .name) |= sub(\"\\\${ACR_NAME}\", \"$ACR_CLEAN_NAME\")
    " "$template_file" >"$output_file"
  # Validar resultado
  if yq eval '.' "$output_file" >/dev/null 2>&1; then
    echo -e "${GREEN}✅ YAML válido gerado: $output_file${NC}"
  else
    echo -e "${RED}❌ YAML inválido gerado${NC}"
    exit 1
  fi
  # Mostrar mudanças
  echo -e "${BLUE}📋 Substituições realizadas:${NC}"
  grep -n "$ACR_CLEAN_NAME" "$output_file" | head -3 || true
  # copiar arquivo final para destino
  cp "$output_file" "$output_file_generated"
}

# Função principal
main() {
  install_yq_if_needed
  load_environment
  process_manifest
  echo -e "${GREEN}🚀 Manifesto pronto para deployment!${NC}"
}

# Executar
main "$@"
