#!/bin/bash
# Generated by Copilot
# Script avançado usando yq para manipulação de YAML

set -euo pipefail

# Cores para output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}🎛️  Gerando manifestos K8s com yq...${NC}"

# Função para instalar yq se necessário
install_yq_if_needed() {
  if ! command -v yq >/dev/null 2>&1; then
    echo -e "${YELLOW}📦 Instalando yq...${NC}"
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
      curl -L "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64" -o /tmp/yq
      sudo mv /tmp/yq /usr/local/bin/yq
      sudo chmod +x /usr/local/bin/yq
    elif [[ "$OSTYPE" == "darwin"* ]]; then
      brew install yq
    else
      echo -e "${RED}❌ Sistema operacional não suportado para instalação automática do yq${NC}"
      exit 1
    fi
    echo -e "${GREEN}✅ yq instalado com sucesso${NC}"
  fi
}
# Carregar configurações
# Carregar configurações
load_environment() {
  # Obter environmentName do azd
  local env_name
  env_name=$(azd env get-values | grep "environmentName=" | cut -d '=' -f2 | tr -d '"')

  if [[ -z "$env_name" ]]; then
    echo -e "${RED}❌ Variável environmentName não definida no azd!${NC}"
    exit 1
  fi

  # Carregar arquivo .env
  local env_file="infra/preset/.env.$env_name"
  if [[ ! -f "$env_file" ]]; then
    echo -e "${RED}❌ Arquivo .env não encontrado: $env_file${NC}"
    exit 1
  fi

  source "$env_file"
  echo -e "${GREEN}✅ Configuração carregada: $env_file${NC}"

  # Validar variáveis obrigatórias
  if [[ -z "$APP_NAME" ]]; then
    echo -e "${RED}❌ APP_NAME não definido no arquivo .env${NC}"
    exit 1
  fi

  if [[ -z "$K8S_RBAC_ENTRA_ADMIN_GROUP_OBJECT_ID" ]]; then
    echo -e "${RED}❌ K8S_RBAC_ENTRA_ADMIN_GROUP_OBJECT_ID não definido no arquivo .env${NC}"
    exit 1
  fi

  echo -e "${BLUE}📝 APP_NAME: ${GREEN}$APP_NAME${NC}"
  echo -e "${BLUE}📝 K8S_RBAC_ENTRA_ADMIN_GROUP_OBJECT_ID: ${GREEN}$K8S_RBAC_ENTRA_ADMIN_GROUP_OBJECT_ID${NC}"
}
# Processar manifesto com yq de forma eficiente
process_manifest() {
  local template_file="infra/cluster-manifests/user-facing-cluster-role-entra-group.template.yaml"
  local output_dir="infra/cluster-manifests/generated"
  local output_file="$output_dir/user-facing-cluster-role-entra-group.yaml"
  local final_output_file="infra/cluster-manifests/user-facing-cluster-role-entra-group.yaml"

  # Verificar template
  if [[ ! -f "$template_file" ]]; then
    echo -e "${RED}❌ Template não encontrado: $template_file${NC}"
    exit 1
  fi

  # Criar diretório
  mkdir -p "$output_dir"

  echo -e "${BLUE}🔄 Processando com yq de forma eficiente...${NC}"

  # Generated by Copilot - Processar YAML com yq de forma otimizada (uma única operação)
  yq eval "
    (.. | select(has(\"name\") and .name == \"\${APP_NAME}-cluster-admins\") | .name) = \"$APP_NAME-cluster-admins\" |
    (.. | select(has(\"name\") and .name == \"\${APP_NAME}-admin\") | .name) = \"$APP_NAME-admin\" |
    (.. | select(has(\"name\") and .name == \"\${APP_NAME}-edit\") | .name) = \"$APP_NAME-edit\" |
    (.. | select(has(\"name\") and .name == \"\${APP_NAME}-view\") | .name) = \"$APP_NAME-view\" |
    (.. | select(has(\"name\") and .name == \"\${K8S_RBAC_ENTRA_ADMIN_GROUP_OBJECT_ID}\") | .name) = \"$K8S_RBAC_ENTRA_ADMIN_GROUP_OBJECT_ID\"
  " "$template_file" >"$output_file"

  # Validar resultado
  if yq eval '.' "$output_file" >/dev/null 2>&1; then
    echo -e "${GREEN}✅ YAML válido gerado: $output_file${NC}"
  else
    echo -e "${RED}❌ YAML inválido gerado${NC}"
    exit 1
  fi

  # Mostrar substituições realizadas
  echo -e "${BLUE}📋 Substituições realizadas:${NC}"
  echo -e "${BLUE}   APP_NAME: ${YELLOW}\${APP_NAME}${BLUE} -> ${GREEN}$APP_NAME${NC}"
  echo -e "${BLUE}   ENTRA_GROUP: ${YELLOW}\${K8S_RBAC_ENTRA_ADMIN_GROUP_OBJECT_ID}${BLUE} -> ${GREEN}$K8S_RBAC_ENTRA_ADMIN_GROUP_OBJECT_ID${NC}"

  # Verificar substituições no arquivo
  local app_name_count=$(grep -c "$APP_NAME" "$output_file" || true)
  local group_id_count=$(grep -c "$K8S_RBAC_ENTRA_ADMIN_GROUP_OBJECT_ID" "$output_file" || true)

  echo -e "${BLUE}📊 Contadores de substituição:${NC}"
  echo -e "${BLUE}   APP_NAME encontrado: ${GREEN}$app_name_count${BLUE} vezes${NC}"
  echo -e "${BLUE}   GROUP_ID encontrado: ${GREEN}$group_id_count${BLUE} vezes${NC}"

  # Copiar arquivo final para destino
  echo -e "${BLUE}📂 Copiando para destino final...${NC}"
  cp "$output_file" "$final_output_file"

  echo -e "${GREEN}✅ Arquivo final criado: $final_output_file${NC}"
}

# Função principal
main() {
  install_yq_if_needed
  load_environment
  process_manifest
  echo -e "${GREEN}🚀 Manifesto pronto para deployment!${NC}"
}

# Executar
main "$@"
