#!/bin/zsh
# Generated by Copilot
# Script funcional para definir variáveis azd

echo "🚀 Configurador de Variáveis AZD - Fabrikam Drone Delivery"
echo ""

# Mostra variáveis atuais
echo "📋 Variáveis atuais:"
azd env get-values
echo ""

# Define as variáveis principais do projeto
echo "🔧 Configurando variáveis essenciais do projeto..."

azd env set DOMAIN_NAME "fabrikam.com"
echo "✅ DOMAIN_NAME definido"

azd env set ENVIRONMENT_NAME "dev"
echo "✅ ENVIRONMENT_NAME definido"

azd env set KUBERNETES_VERSION "1.30.12"
echo "✅ KUBERNETES_VERSION definido"

azd env set APP_NAME "fabrikam-dronedelivery"
echo "✅ APP_NAME definido"

echo ""
echo "🎉 Configuração concluída!"
echo ""
echo "📋 Variáveis finais:"
azd env get-values
echo ""
echo "🚀 Próximo passo: azd up"
