#!/bin/zsh
# Generated by Copilot
# Script para configurar todas as variáveis necessárias do projeto Fabrikam Drone Delivery
if [ -z "$ZSH_VERSION" ]; then
    echo -e "${YELLOW}⚠️ Este script foi otimizado para Zsh, mas pode funcionar em outras shells.${NC}"
fi
if ! command -v azd &> /dev/null; then
    echo -e "${RED}❌ O Azure Developer CLI (azd) não está instalado!${NC}"
    exit 1
fi
# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}=================================================="
echo -e "  🚁 Fabrikam Drone Delivery - Setup Completo"
echo -e "==================================================${NC}"
echo ""
environmentName=$(azd env get-values | grep "environmentName=" | cut -d '=' -f2 | tr -d '"')
if [[ -z "$environmentName" ]]; then
    echo -e "${RED}❌ Variável environmentName não definida no azd!${NC}"
    exit 1
fi
envFile="infra/preset/.env.$environmentName"
if [[ ! -f "$envFile" ]]; then
    echo -e "${RED}❌ Arquivo .env não encontrado: $envFile${NC}"
    exit 1
else
    source "$envFile"
    echo -e "${GREEN}✅ Arquivo .env carregado!${NC}"
fi
# Função para definir variável com feedback
set_var() {
    local name=$1
    local value=$2
    local description=$3
    
    echo -e "${BLUE}📝 Definindo $name...${NC}"
    if azd env set "$name" "$value"; then
        echo -e "${GREEN}  ✅ $description${NC}"
    else
        echo -e "${RED}  ❌ Erro ao definir $name${NC}"
        return 1
    fi
}
# normalizacao booleano
normalize_boolean() {
    local value=$1
    local var_name=$2
    
    # Converte para minúsculo e remove espaços
    value=$(echo "$value" | tr '[:upper:]' '[:lower:]' | tr -d ' ')
    
    case "$value" in
        "true"|"1"|"yes"|"on"|"enabled")
            echo "true"
            ;;
        "false"|"0"|"no"|"off"|"disabled"|"")
            echo "false"
            ;;
        *)
            echo -e "${YELLOW}⚠️ Valor inválido para $var_name: '$value'. Usando 'false' como padrão.${NC}"
            echo "false"
            ;;
    esac
}

# Função para definir variável booleana
set_boolean_var() {
    local name=$1
    local value=$2
    local description=$3
    
    # Normaliza o valor booleano
    local normalized_value=$(normalize_boolean "$value" "$name")
    
    echo -e "${BLUE}📝 Definindo $name como booleano...${NC}"
    if azd env set "$name" "$normalized_value"; then
        echo -e "${GREEN}  ✅ $description: $normalized_value${NC}"
    else
        echo -e "${RED}  ❌ Erro ao definir $name${NC}"
        return 1
    fi
}

echo -e "${BLUE}🔧 Configurando variáveis do projeto Fabrikam Drone Delivery...${NC}"
echo ""

# Variáveis básicas do projeto
set_variable "environmentName" $ENVIRONMENT_NAME
    set_var "location" $AZURE_LOCATION
    set_var "geoRedundancyLocation" $GEO_REDUNDANCY_LOCATION 
    set_var "azureTenantId" $AZURE_TENANT_ID
    set_var "azureSubscriptionId" $AZURE_SUBSCRIPTION_ID
    set_var "appName" $APP_NAME
    set_var "domainName" $DOMAIN_NAME
    set_var "kubernetesVersion" $KUBERNETES_VERSION
    set_var "k8sRbacEntraProfileTenantId" $K8S_RBAC_ENTRA_PROFILE_TENANT_ID
    set_var "k8sRbacEntraAdminGroupObjectID" $K8S_RBAC_ENTRA_ADMIN_GROUP_OBJECT_ID

# Configurações Azure já existentes (verificamos se precisam ser atualizadas)
existing_location=$(azd env get-value "location" 2>/dev/null || echo "")
if [[ "$existing_location" != $AZURE_LOCATION ]]; then
    set_var "location" $AZURE_LOCATION "Localização do Azure"
fi

# Configurações específicas do AKS
set_var "aksSystemNodeCount" $AKS_SYSTEM_NODE_COUNT "Número de nós do AKS - System"
set_var "aksUserNodeCount" $AKS_USER_NODE_COUNT "Número de nós do AKS - User"
set_var "aksNodeSize" $AKS_NODE_SIZE "Tamanho dos nós do AKS"
set_var "aksEnableAutoScaling" $AKS_ENABLE_AUTO_SCALING "Auto scaling habilitado"
set_var "aksMinCount" $AKS_MIN_COUNT "Mínimo de nós"
set_var "aksMaxCount" $AKS_MAX_COUNT "Máximo de nós"
set_var "aksServiceCidr" $AKS_SERVICE_CIDR
set_var "aksDnsServiceIP" $AKS_DNS_SERVICE_IP
set_var "aksLoadBalancerSku" $AKS_LOAD_BALANCER_SKU

# Configurações de aplicação
set_var "APP_NAME" $APP_NAME "Nome da aplicação"
set_var "APP_VERSION" $APP_VERSION "Versão da aplicação"

# Configurações de monitoramento
set_boolean_var "ENABLE_MONITORING" $ENABLE_MONITORING "Monitoramento habilitado"
set_var "LOG_LEVEL" $LOG_LEVEL "Nível de log"

# Configurações de segurança
set_boolean_var "ENABLE_RBAC" $ENABLE_RBAC "RBAC habilitado"
set_boolean_var "ENABLE_NETWORK_POLICY" $ENABLE_NETWORK_POLICY "Network Policy habilitado"

echo ""
echo -e "${GREEN}🎉 Configuração completa!${NC}"
echo ""
echo -e "${CYAN}📋 Resumo das variáveis configuradas:${NC}"
azd env get-values | sort

echo ""
echo -e "${BLUE}🚀 Próximos passos:${NC}"
echo "1. Execute: azd up (para fazer deploy completo)"
echo "2. Ou execute: azd provision (apenas infraestrutura)"
echo "3. Execute: azd deploy (apenas aplicações)"
echo ""
